[package]
name = 'rgbio'
publish = false
version = '0.2.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'rgbio'

[dependencies]
extendr-api = '0.8.1'
gb-io = "0.9.0"

[profile.release]
lto = true
codegen-units = 1
