name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v3

      - uses: r-lib/actions/setup-r@v3
        with:
          r-version: "release"

      - uses: r-lib/actions/setup-r-dependencies@v3
        with:
          extra-packages: any::pkgdown
          needs: website

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build site
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to gh-pages
        if: ${{ github.event_name == 'push' }}
        uses: r-lib/actions/deploy-pkgdown@v3
        with:
          branch: gh-pages
